dataset_csv_path: 'dataset/1D_compressor_geometry_normalised.csv'
data_structure: '1D_params' 
neural_network_sturcture: 'ResNet_UNet'
learning_rate: 1E-4
num_epochs: 100
batch_size: 64
model_channel: 64  # the number of channels for of first layer
model_layer: 5      # number of layers under the same dimension
model_channel_multiplication: [1,2,4,8] # dimension multiplication factor
train_val_division: 0.8 # training set percent
cond_scale: 1    # CFG guidance scale
rescaled_phi: 0  # Mixing ratio of the std_function
device: 'cuda'
component_number: 16
restart: False
reduced_data_fraction: 0.7