import os
import math
import pandas as pd

class Convert_surfaces_csv_to_curve_files:

    def __init__(self,path_to_folder,splitter_blades,extreme_value, vaneless_existence, b_2, b_3, r_3, pinching, pinching_ratio, curve_directory):
        
        self.path_to_folder = path_to_folder
        self.splitter_blades = splitter_blades
        self.extreme_value = extreme_value
        self.pinching_ratio = pinching_ratio
        self.curve_directory = curve_directory
        self.main_blade_path = os.path.join(path_to_folder,'Main_Blades')

        if splitter_blades == True:
            self.splitter_blade_path = os.path.join(path_to_folder,'Splitter_Blades')

        self.vaneless_existence = vaneless_existence
        self.b_2 = b_2
        self.b_3 = b_3
        self.r_3 = r_3
        self.pinching = pinching


    def identify_csv_files(self,path_to_folder):
        """
        Function to identify the individual csv files of surfaces generated by the blade forming
        software
        """
        
        filenames = ['le_surface.csv','ps_surface.csv', 'ss_surface.csv']
        file_paths = []
        
        # Walk through all files and directories within the specified directory
        for root, dirs, files in os.walk(path_to_folder):
            for file in files:
                if file in filenames:
                    file_paths.append(os.path.join(root, file))
        
        return file_paths
    



    def read_first_line_numbers(self, file_path):
        with open(file_path, 'r') as file:
            first_line = file.readline().strip()
            numbers = [int(num) for num in first_line.split(',')]
        return numbers



    def create_hub_curve_file(self, extreme_value, vaneless_existence, r_3):
        """
        Creates the hub .curve file for the 3D compressor geometry.
        If vaneless_existence is True, extends the radius up to r_3.
        If self.pinching is True, includes the pinching-related extension.
        """
       
        # form the paths of the input and output files
        hub_path = os.path.join(self.main_blade_path, 'hub.dat')
        curve_path = os.path.join(self.curve_files_dir, 'HubOriginal.curve')

        # Ensure the directory exists
        os.makedirs(self.curve_files_dir, exist_ok=True)

        # Read the contents of the hub.dat file
        with open(hub_path, 'r') as file:
            lines = file.readlines()

        # Process lines to add a zero column
        processed_lines = [line.strip() + ' 0\n' if len(line.strip().split()) == 2 else line for line in lines]

        # Use the second and third columns of the first processed line for the extreme values
        first_line_parts = processed_lines[0].strip().split()
        base_value2 = first_line_parts[1]  # Radius
        base_value3 = first_line_parts[2]  # z-value

        # Prepare the extreme value lines
        extreme_lines = [f"{i} {base_value2} {base_value3}\n" for i in range(extreme_value, 0)]

        # Combine all lines
        all_lines = extreme_lines + processed_lines

        # Get last line data
        last_line_parts = all_lines[-1].strip().split()
        original_x = float(last_line_parts[0])
        original_radius = float(last_line_parts[1])
        z_value = last_line_parts[2]

        # Initialize variables for further extensions
        x_h_start = original_x
        r_h_start = original_radius

        ###### If vaneless diffuser exists, extend radius up to r_3 ######################
        if vaneless_existence and original_radius < r_3:

            num_extension_to_r3 = 50  # Number of points for the extension to r_3
            delta_radius_to_r3 = (r_3 - original_radius) / num_extension_to_r3

            for i in range(1, num_extension_to_r3 + 1):

                new_radius = original_radius + i * delta_radius_to_r3
                new_line = f"{original_x} {new_radius} {z_value}\n"
                all_lines.append(new_line)
            
            # Update original_radius for next extensions
            original_radius = r_3
            r_h_start = original_radius  # Update starting radius for further extensions

        # Proceed with extensions
        num_extension_points = 50  # Number of points for the extension (parallel wall or pinching-related)
        num_additional_extension_points = 50  # Number of points for the additional extension (pinching-related)

        if not vaneless_existence:

            # Parallel wall extension prior to pinching
            extended_radius_1 = original_radius * 1.35  # +35%
            delta_radius_1 = (extended_radius_1 - original_radius) / num_extension_points
            
            for i in range(1, num_extension_points + 1):
                new_radius = original_radius + i * delta_radius_1
                new_line = f"{original_x} {new_radius} {z_value}\n"
                all_lines.append(new_line)
            
            # Update variables for further extensions
            r_h_start = extended_radius_1
        
        else:
            
            # Skip parallel wall extension
            extended_radius_1 = r_h_start  # Use current radius as starting point

        # Include pinching-related extension only if self.pinching is True
        if self.pinching:
            # Extension corresponding to pinching
            # Compute the final extended radius (e.g., additional 11.1% increase)
            extended_radius_2 = extended_radius_1 * 1.211  # +11.1% of extended_radius_1

            delta_radius_2 = (extended_radius_2 - extended_radius_1) / num_additional_extension_points
            for i in range(1, num_additional_extension_points + 1):
                new_radius = extended_radius_1 + i * delta_radius_2
                new_line = f"{original_x} {new_radius} {z_value}\n"
                all_lines.append(new_line)
            print(f"Hub curve file created at {curve_path} (included pinching-related extension).")
        else:
            print(f"Hub curve file created at {curve_path} (pinching-related extension skipped).")

        # Write the contents to the new curve file
        with open(curve_path, 'w') as file:
            file.writelines(all_lines)




    def create_shroud_curve_file(
            self,
            extreme_value: int,
            vaneless_existence: bool,
            r_3: float,
            b_2: float,
            b_3: float
        ):
        """
        Build ShroudOriginal.curve.

        ── New rule when *vaneless_existence is True* ──────────────────────────
        • From r = r₂  (impeller exit)                                     │
          to r = r₂ + b₂  (Δr = b₂)  → “taper zone”                        │
              – width b shrinks linearly  b₂ → b₃                          │
              – shroud-x therefore moves downstream linearly               │
        • From r = r₂ + b₂  to r = r₃ → “constant zone”                    │
              – width remains b₃, shroud-x frozen                          │
        ──────────────────────────────────────────────────────────────────────
        All other branches (no vaneless, pinching) behave as before.
        """

        # ----------------------------- constants ---------------------------
        NUM_TAPER_POINTS   = 50      # pts for taper zone  (Δr = b₂)
        NUM_CONST_POINTS   = 50      # pts for constant-width zone  (r₂+b₂ → r₃)
        NUM_PAR_WALL_PTS   = 50      # pts for parallel wall when *no* vaneless
        NUM_PINCH_PTS      = 50      # pts *excluding* the first node (so +1 later)

        casing_path = os.path.join(self.main_blade_path, 'casing.dat')
        curve_path  = os.path.join(self.curve_files_dir, 'ShroudOriginal.curve')
        os.makedirs(self.curve_files_dir, exist_ok=True)

        # ---------------------- read raw shroud file -----------------------
        with open(casing_path, 'r') as f:
            lines = f.readlines()

        processed_lines = [ln.strip() + ' 0\n' if ' 0' not in ln else ln
                           for ln in lines]

        # prepend the “extreme” dummy rows
        first_parts = processed_lines[0].strip().split()
        extreme_lines = [f"{i} {first_parts[1]} {first_parts[2]}\n"
                         for i in range(extreme_value, 0)]
        all_lines = extreme_lines + processed_lines

        # --------------------------- hub info ------------------------------
        hub_curve_path = os.path.join(self.curve_files_dir, 'HubOriginal.curve')
        with open(hub_curve_path, 'r') as hf:
            last_hub_x = float(hf.readlines()[-1].split()[0])

        # ------------------ state at the impeller exit ---------------------
        last_parts      = all_lines[-1].split()
        x_s_current     = float(last_parts[0])        # shroud-x at r₂
        r_s_current     = float(last_parts[1])        # = r₂
        z_value         = last_parts[2]               # unchanged later

        # ===================================================================
        # 1. VANELESS DIFFUSER BRANCH  (the new taper+constant rule)
        # ===================================================================
        if vaneless_existence and r_s_current < r_3:

            # ---- guard rails
            if b_2 is None or b_3 is None:
                raise ValueError("b_2 and b_3 must be provided for vaneless diffuser.")

            if b_3 > b_2:
                raise ValueError("b_3 should not be larger than b_2.")

            # ---------------------------------------------------------------
            # Phase A  ·  linear taper  Δr = b₂  (or less if r₃ is closer)
            # ---------------------------------------------------------------
            taper_end_radius = r_s_current + b_2
            taper_end_radius = min(taper_end_radius, r_3)          # clamp

            Δr_taper  = taper_end_radius - r_s_current
            Δx_total  = b_2 - b_3                    # shroud-x shift needed
            # scale shift if taper is shorter than full b₂
            Δx_total *= (Δr_taper / b_2) if b_2 != 0 else 0.0
            Δr_step   = Δr_taper / NUM_TAPER_POINTS
            Δx_step   = Δx_total / NUM_TAPER_POINTS

            for i in range(1, NUM_TAPER_POINTS + 1):
                new_r = r_s_current + i * Δr_step
                new_x = x_s_current + i * Δx_step
                all_lines.append(f"{new_x} {new_r} {z_value}\n")

            # update “current” position after taper
            x_s_current += Δx_total
            r_s_current  = taper_end_radius

            # ---------------------------------------------------------------
            # Phase B  ·  constant-width run-out to r₃  (if any Δr left)
            # ---------------------------------------------------------------
            if r_s_current < r_3:
                Δr_const  = r_3 - r_s_current
                Δr_step_c = Δr_const / NUM_CONST_POINTS

                for i in range(1, NUM_CONST_POINTS + 1):
                    new_r = r_s_current + i * Δr_step_c
                    all_lines.append(f"{x_s_current} {new_r} {z_value}\n")

                r_s_current = r_3                         # finished vaneless

            # pinching (if selected) will start from x_s_current / r_s_current
            x_s_start = x_s_current
            r_s_start = r_s_current

        # ===================================================================
        # 2. NO-VANELESS  → keep old logic (parallel wall + pinching)
        # ===================================================================
        else:
            # ---------------- parallel-wall extension (+35 % radius) -------
            extended_r1 = r_s_current * 1.35
            Δr_pw = (extended_r1 - r_s_current) / NUM_PAR_WALL_PTS

            for i in range(1, NUM_PAR_WALL_PTS + 1):
                new_r = r_s_current + i * Δr_pw
                all_lines.append(f"{x_s_current} {new_r} {z_value}\n")

            x_s_start = x_s_current
            r_s_start = extended_r1
            r_s_current = extended_r1   # for pinching later

        # ===================================================================
        # 3. PINCHING  (same as before)
        # ===================================================================
        if self.pinching:
            r_s_end = r_s_start * 1.211
            area_ratio = self.pinching_ratio
            x_h = last_hub_x
            x_s_end = x_h + (r_s_start * (x_s_start - x_h) * area_ratio) / r_s_end

            num_total = NUM_PINCH_PTS + 1
            for i in range(num_total + 1):
                t = i / num_total
                r = r_s_start + (r_s_end - r_s_start) * t
                x = x_s_start + (x_s_end - x_s_start) * (1 - math.cos(math.pi * t)) / 2
                all_lines.append(f"{x} {r} {z_value}\n")
            print(f"Shroud curve file created at {curve_path} (included pinching phase).")
        else:
            print(f"Shroud curve file created at {curve_path} (pinching phase skipped).")

        # ===================================================================
        # 4. Write file
        # ===================================================================
        with open(curve_path, 'w') as f_out:
            f_out.writelines(all_lines)






    def create_blade_curve_file(self, blade_type):
        """
        Function to create curve file for a blade
        """
        
        if blade_type == 'main':
            csv_directory = self.main_blade_path
            curve_path = os.path.join(self.curve_files_dir, 'BladeMain.curve')
        else:
            csv_directory = self.splitter_blade_path
            curve_path = os.path.join(self.curve_files_dir, 'BladeSplitter.curve')

        self.le_surface, self.ps_surface, self.ss_surface = self.identify_csv_files(csv_directory)

        num_components_ps, num_profiles = self.read_first_line_numbers(self.ps_surface)
        num_components_ss = self.read_first_line_numbers(self.ss_surface)[0]
        num_components_le = self.read_first_line_numbers(self.le_surface)[0]

        with open(curve_path, 'w') as curve_file:
            curve_file.write(f"## {'Main Blade' if blade_type == 'main' else 'Splitter Blade'}\n")

            for profile in range(1, num_profiles + 1):
                curve_file.write(f"#Profile {profile}\n")

                # Writing ps_surface data
                ps_df = pd.read_csv(self.ps_surface, skiprows=1, header=None)
                start_ps = (profile - 1) * num_components_ps
                end_ps = start_ps + num_components_ps
                ps_data = ps_df[start_ps:end_ps].to_csv(header=False, index=False)
                curve_file.write(ps_data.replace('\r\n', '\n'))
                
                # Writing ss_surface data
                ss_df = pd.read_csv(self.ss_surface, skiprows=1, header=None)
                start_ss = (profile - 1) * num_components_ss
                end_ss = start_ss + num_components_ss
                ss_data = ss_df[start_ss:end_ss].iloc[::-1].to_csv(header=False, index=False)
                curve_file.write(ss_data.replace('\r\n', '\n'))

                # Writing le_surface data
                le_df = pd.read_csv(self.le_surface, skiprows=1, header=None)
                start_le = (profile - 1) * num_components_le + 1
                end_le = start_le + num_components_le-1
                le_data = le_df[start_le:end_le].to_csv(header=False, index=False)
                curve_file.write(le_data.replace('\r\n', '\n'))




    def create_curve_files(self):
        """
        Function to create the curve files for the compressor
        """

        # create a directory to store the .curve files
        self.curve_files_dir = self.curve_directory
        if not os.path.exists(self.curve_files_dir):
            os.makedirs(self.curve_files_dir)

        # for main
        # identify the csv files with the generated surfaces
        self.le_surface, self.ps_surface, self.ss_surface = self.identify_csv_files(self.main_blade_path)
        
        # create the HubOriginal.curve file
        self.create_hub_curve_file(self.extreme_value, self.vaneless_existence, self.r_3)

        # create the ShroudOriginal.curve file
        self.create_shroud_curve_file(self.extreme_value, self.vaneless_existence, self.r_3, self.b_2, self.b_3)

        # create the BladeMain.curve file 
        self.create_blade_curve_file('main')

        if self.splitter_blades == True:
            self.create_blade_curve_file('splitter')